"""initial schema

Revision ID: 623c57886e29
Revises: 
Create Date: 2026-07-12 20:58:35.221373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623c57886e29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_session_id'), 'traces', ['session_id'], unique=False)
    op.create_table('spans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('parent_span_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('span_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_span_id'], ['spans.id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spans_parent_span_id'), 'spans', ['parent_span_id'], unique=False)
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('span_id', sa.String(length=36), nullable=True),
    sa.Column('evaluator_type', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['span_id'], ['spans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_span_id'), 'evaluations', ['span_id'], unique=False)
    op.create_index(op.f('ix_evaluations_trace_id'), 'evaluations', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_trace_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_span_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_parent_span_id'), table_name='spans')
    op.drop_table('spans')
    op.drop_index(op.f('ix_traces_session_id'), table_name='traces')
    op.drop_table('traces')
    # ### end Alembic commands ###
